### ISSUE TITLE
Account emails get HTML encoded and fail

### ISSUE THREAD

**Issue by Travers** [chb/indivo_ui_server#14]
Accounts with emails such as `TestyMc'Tester@test.com` will fail to load since the `'` gets html encoded.

**Comment by p2** [comment]
Is this a valid email address? Wow.

**Comment by Travers** [comment]
yeah, you can have crazy stuff like `"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com` , but most places are going to give you problems if you have one like that.  We should probably also worry more about emails with unicode...
