### ISSUE TITLE
Production Javascript Compression Problem

### ISSUE THREAD

**Issue by JooHyoungLee** [chb/indivo_ui_server#16]
The following commands were executed.

/indivo_ui_server/ui/jmvc/$ ./js steal/buildjs http://localhost -to ui

Building to ui/

So End commands.

Not Run 
BUILDING STYLES --------------- 
BUILDING SCRIPTS --------------- 
.
.
.
.

My Environment is Ubuntu server
Java version is 1.6

Do you have information I need to check?

**Comment by Travers** [comment]
Make sure to uncomment the line
`<script compress="true" type="text/javascript" src="/jmvc/steal/steal.js?ui,development"></script>`
from `/indivo_ui_server/templates/ui/base.html` and comment out the `<script>` tags from `/indivo_ui_server/templates/ui/header.html` before running this command.  Also make sure you can access the Indivo UI server at http://localhost
