### ISSUE TITLE
Valid email containing a + character treated as invalid

### ISSUE THREAD

**Issue by focusaurus** [chb/indivo_ui_server#6]
I was testing account registration and tried using an email with a plus sign like example+1@example.com, which is valid, but the registration form highlights it as an error. Remove the "+" and all is well. This is most likely just a bug in the email regex. This is handy because gmail accounts can be account+whatever@gmail.com and will all route to the "account" gmail account.

**Comment by Travers** [comment]
Agreed, it looks like the current regex check is too restrictive.
