### ISSUE TITLE
Patient display name in the Indivo Developer's Sandbox

### ISSUE THREAD

**Issue by rloftin** [chb/indivo_ui_server#7]
Based on the data returned in response to a SMART Demographic api call, the Indivo sandbox uses the &lt;family-name&gt; / &lt;given-name&gt; format for displaying patient name in its Tabs (i.e. Ruth Black, Mary Long, William Robinson).  However, when &lt;family-name&gt; precedes &lt;given-name&gt;, it is customary to include a comma between the &lt;family-name&gt; and &lt;given-name&gt; so as avoid confusion.  For example, this would result in a change in the way in which patient name is displayed on the tabs within the Indivo developers sandbox i.e. instead of "Ruth Black", it would be "Ruth, Black".

Or, could it be that the implementation of the SMART Demographic api call in the Indivo Developer's sandbox has mistakenly placed the name data into the wrong fields i.e. instead of "Ruth" being placed in the &lt;family-name&gt; field it should have been placed in the &lt;given-name&gt; field?

**Comment by p2** [comment]
The **order** of the data should not matter as it is RDF, but if you're getting "Ruth" in the `family-name` field, then that's definitely wrong!

**Comment by rloftin** [comment]
I am getting "Ruth" in the &lt;family-name&gt; field.  However, if that is corrected, it would seem that the display name on the tab still has to be changed because it displays &lt;family-name&gt; before &lt;given-name&gt;

**Comment by p2** [comment]
Yes, that's indeed being returned mixed up! Looking through the code though this probably happened when importing  sample data, seems correct internally. I'll let @Travers confirm that.

The tabs display the record's `label` property, which is its own string and can be changed with this call:

```
PUT /records/{RECORD_ID}/documents/{DOCUMENT_ID}/label
```

**Comment by p2** [comment]
The sample data indeed has family-name and given-name reversed, so I'm closing this issue, referring to:

https://github.com/chb/indivo_server/issues/25
